In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulation

In [3]:
arr = np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[1, 8, 7, 1],
       [3, 2, 6, 6],
       [9, 1, 8, 7],
       [3, 1, 8, 2]])

In [5]:
arr.reshape(8,2) ## Using the reshape you will convert a array into any shape

array([[1, 8],
       [7, 1],
       [3, 2],
       [6, 6],
       [9, 1],
       [8, 7],
       [3, 1],
       [8, 2]])

In [6]:
## How to rotate a entire array 
arr

array([[1, 8, 7, 1],
       [3, 2, 6, 6],
       [9, 1, 8, 7],
       [3, 1, 8, 2]])

In [7]:
arr.T

array([[1, 3, 9, 3],
       [8, 2, 1, 1],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

In [9]:
arr.flatten() ## flatten is convert the array into one dimensional array.

array([1, 8, 7, 1, 3, 2, 6, 6, 9, 1, 8, 7, 3, 1, 8, 2])

In [10]:
arr

array([[1, 8, 7, 1],
       [3, 2, 6, 6],
       [9, 1, 8, 7],
       [3, 1, 8, 2]])

In [12]:
np.expand_dims(arr,axis=1)

array([[[1, 8, 7, 1]],

       [[3, 2, 6, 6]],

       [[9, 1, 8, 7]],

       [[3, 1, 8, 2]]])

In [13]:
np.expand_dims(arr,axis=0)

array([[[1, 8, 7, 1],
        [3, 2, 6, 6],
        [9, 1, 8, 7],
        [3, 1, 8, 2]]])

In [14]:
data = np.array([[1] , [2] , [3]])

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [17]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [18]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
##Numpy - Binary Operation.

In [20]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [21]:
arr1

array([[1, 5, 5, 6],
       [4, 3, 9, 7],
       [8, 9, 3, 2]])

In [22]:
arr2

array([[7, 8, 7, 7],
       [2, 2, 2, 3],
       [5, 3, 4, 7]])

In [23]:
arr1+arr2

array([[ 8, 13, 12, 13],
       [ 6,  5, 11, 10],
       [13, 12,  7,  9]])

In [24]:
arr1*arr2

array([[ 7, 40, 35, 42],
       [ 8,  6, 18, 21],
       [40, 27, 12, 14]])

In [25]:
arr1/arr2

array([[0.14285714, 0.625     , 0.71428571, 0.85714286],
       [2.        , 1.5       , 4.5       , 2.33333333],
       [1.6       , 3.        , 0.75      , 0.28571429]])

In [26]:
arr1-arr2

array([[-6, -3, -2, -1],
       [ 2,  1,  7,  4],
       [ 3,  6, -1, -5]])

In [27]:
arr1**arr2

array([[     1, 390625,  78125, 279936],
       [    16,      9,     81,    343],
       [ 32768,    729,     81,    128]])

In [28]:
~arr1

array([[ -2,  -6,  -6,  -7],
       [ -5,  -4, -10,  -8],
       [ -9, -10,  -4,  -3]])

In [30]:
arr1

array([[1, 5, 5, 6],
       [4, 3, 9, 7],
       [8, 9, 3, 2]])

In [31]:
arr1>arr2

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [32]:
#Numpy - String Function.

In [35]:
arr = np.array(["adil","mirza"])

In [36]:
arr

array(['adil', 'mirza'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['ADIL', 'MIRZA'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Adil', 'Mirza'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Adil', 'Mirza'], dtype='<U5')

In [40]:
##Numpy - Mathematical Functios

In [41]:
arr1

array([[1, 5, 5, 6],
       [4, 3, 9, 7],
       [8, 9, 3, 2]])

In [44]:
# how to know the sinosudal values 
np.sin(arr1)

array([[ 0.84147098, -0.95892427, -0.95892427, -0.2794155 ],
       [-0.7568025 ,  0.14112001,  0.41211849,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.14112001,  0.90929743]])

In [45]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219,  0.28366219,  0.96017029],
       [-0.65364362, -0.9899925 , -0.91113026,  0.75390225],
       [-0.14550003, -0.91113026, -0.9899925 , -0.41614684]])

In [46]:
np.tan(arr1)

array([[ 1.55740772, -3.38051501, -3.38051501, -0.29100619],
       [ 1.15782128, -0.14254654, -0.45231566,  0.87144798],
       [-6.79971146, -0.45231566, -0.14254654, -2.18503986]])

In [47]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.69897   , 0.77815125],
       [0.60205999, 0.47712125, 0.95424251, 0.84509804],
       [0.90308999, 0.95424251, 0.47712125, 0.30103   ]])

In [48]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 1.48413159e+02, 4.03428793e+02],
       [5.45981500e+01, 2.00855369e+01, 8.10308393e+03, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.00855369e+01, 7.38905610e+00]])

In [49]:
np.power(arr1,2)

array([[ 1, 25, 25, 36],
       [16,  9, 81, 49],
       [64, 81,  9,  4]])

In [50]:
np.mean(arr1)

5.166666666666667

In [51]:
np.median(arr1)

5.0

In [53]:
np.std(arr1)

2.576604138956718

In [54]:
np.var(arr1)

6.63888888888889

In [55]:
np.min(arr1)

1

In [57]:
np.max(arr1)

9

In [58]:
# Numpy - Arithmetic Operation

In [59]:
arr1

array([[1, 5, 5, 6],
       [4, 3, 9, 7],
       [8, 9, 3, 2]])

In [60]:
arr2

array([[7, 8, 7, 7],
       [2, 2, 2, 3],
       [5, 3, 4, 7]])

In [61]:
arr1-arr2

array([[-6, -3, -2, -1],
       [ 2,  1,  7,  4],
       [ 3,  6, -1, -5]])

In [62]:
np.subtract(arr1,arr2)

array([[-6, -3, -2, -1],
       [ 2,  1,  7,  4],
       [ 3,  6, -1, -5]])

In [63]:
np.multiply(arr1,arr2)

array([[ 7, 40, 35, 42],
       [ 8,  6, 18, 21],
       [40, 27, 12, 14]])

In [64]:
np.mod(arr1,arr2)

array([[1, 5, 5, 6],
       [0, 1, 1, 1],
       [3, 0, 3, 2]])

In [65]:
np.power(arr1,arr2)

array([[     1, 390625,  78125, 279936],
       [    16,      9,     81,    343],
       [ 32768,    729,     81,    128]])

In [66]:
np.sqrt(arr1)

array([[1.        , 2.23606798, 2.23606798, 2.44948974],
       [2.        , 1.73205081, 3.        , 2.64575131],
       [2.82842712, 3.        , 1.73205081, 1.41421356]])

In [67]:
#Numpy - Statistical Fuction

In [68]:
arr1

array([[1, 5, 5, 6],
       [4, 3, 9, 7],
       [8, 9, 3, 2]])

In [69]:
# Find average of it
np.mean(arr1)

5.166666666666667

In [70]:
np.std(arr1)

2.576604138956718

In [71]:
np.median(arr1)

5.0